[package]
name = "ssh-chat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rpassword = "7.3.1"
ssh-key = { version = "0.6.3", features = ["std", "crypto", "encryption"] }
